name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.LOWLIGHTERMETRICS }}
          user: cromanpa94
          template: classic
          base: header, activity, community, repositories, metadata
          config_animations: yes
          config_timezone: America/Phoenix
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year         
          plugin_languages: yes
          plugin_languages_ignored: html, css, scss, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, JavaScript, Ruby
          plugin_lines: yes
          plugin_stars: yes
          plugin_stars_limit: 3
          plugin_habits: yes
          plugin_habits_from: 250
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
